INSERT INTO POSTS (USER_ID, BODY) VALUES (1, "New post before delete");

SELECT * FROM POSTS;

UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 8;

SELECT * FROM POSTS;

DELETE FROM POSTS
WHERE BODY = "To delete";

SELECT * FROM POSTS;